### ISSUE TITLE
Items todo before publishing to Pypi

### ISSUE THREAD

**Issue by Ashton-Sidhu** [hiddenlayerai/hiddenlayer-sdk-python#1]
## Summary

This ticket is to serve as a todo list of items before we publish version `0.1.0` on pypi.

### Release tasks
- [x] Publish docs to readthedocs
- [x] Add CD to Twine
- [x] Touch base with support/sales to let them know that this is our official Python SDK that customers can use and is fully supported.
- [x] Create PR template
- [x] Create Issue template
- [x] Add code examples
- [x] Agree on licensing
- [x] Finalize model scan function integrations we want to create
